const CREATE_PERMISSION = "CREATE";
const UPDATE_PERMISSION = "UPDATE";
const DELETE_PERMISSION = "DELETE";
const EXECUTE_PERMISSION = "EXECUTE";

const MASTER_REGISTRY_RESOURCE = "MASTER_REGISTRY_RESOURCE";
const CONSTANTS_REGISTRY_RESOURCE = "CONSTANTS_REGISTRY_RESOURCE";
const REVIEWABLE_REQUESTS_RESOURCE = "REVIEWABLE_REQUESTS_RESOURCE";

const RequestStatus = {
  NONE: 0,
  PENDING: 1,
  ACCEPTED: 2,
  REJECTED: 3,
  DROPPED: 4,
};

module.exports = {
  CREATE_PERMISSION,
  UPDATE_PERMISSION,
  DELETE_PERMISSION,
  EXECUTE_PERMISSION,
  MASTER_REGISTRY_RESOURCE,
  CONSTANTS_REGISTRY_RESOURCE,
  REVIEWABLE_REQUESTS_RESOURCE,
  RequestStatus,
};
