export const CREATE_PERMISSION = "CREATE";
export const UPDATE_PERMISSION = "UPDATE";
export const DELETE_PERMISSION = "DELETE";
export const EXECUTE_PERMISSION = "EXECUTE";

export const MASTER_REGISTRY_RESOURCE = "MASTER_REGISTRY_RESOURCE";
export const CONSTANTS_REGISTRY_RESOURCE = "CONSTANTS_REGISTRY_RESOURCE";
export const REVIEWABLE_REQUESTS_RESOURCE = "REVIEWABLE_REQUESTS_RESOURCE";

export const RequestStatus = {
  NONE: 0,
  PENDING: 1,
  ACCEPTED: 2,
  REJECTED: 3,
  DROPPED: 4,
};
